
-----------------------------------------
时间:2017-11-08 10:37:08,157 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.MainRegionViewModel.<LoginManage_LoginChanged>d__164.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\MainRegionViewModel.cs:行号 615

-----------------------------------------
时间:2017-11-08 10:37:27,093 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.LoginViewModel.<LoginManage_LoginChanged>d__24.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\LoginViewModel.cs:行号 126

-----------------------------------------
时间:2017-11-08 10:37:27,165 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.MainRegionViewModel.<LoginManage_LoginChanged>d__164.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\MainRegionViewModel.cs:行号 615

-----------------------------------------
时间:2017-11-08 10:41:02,891 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.Exception: 数据库初始化失败 ---> System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 373
   --- 内部异常堆栈跟踪的结尾 ---
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 377
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.DatabaseService.LoginUserService.<LazyLoading>d__25.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 174
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.LoginViewModel.<LoginManage_LoginChanged>d__24.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\LoginViewModel.cs:行号 130

-----------------------------------------
时间:2017-11-08 10:41:02,906 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:mscorlib
-----------------------------------------

System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 373

-----------------------------------------
时间:2017-11-08 10:41:09,660 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.Exception: 数据库初始化失败 ---> System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 373
   --- 内部异常堆栈跟踪的结尾 ---
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 377
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.DatabaseService.LoginUserService.<LazyLoading>d__25.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 174
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.LoginViewModel.<LoginManage_LoginChanged>d__24.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\LoginViewModel.cs:行号 130

-----------------------------------------
时间:2017-11-08 10:41:09,661 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:mscorlib
-----------------------------------------

System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 AIC.DatabaseService.DatabaseComponent.<LoadHardwave>d__54.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\DatabaseComponent.cs:行号 373

-----------------------------------------
时间:2017-11-08 10:41:20,459 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.MainRegionViewModel.<LoginManage_LoginChanged>d__164.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\MainRegionViewModel.cs:行号 615

-----------------------------------------
时间:2017-11-08 10:41:20,570 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.MainRegionViewModel.<LoginManage_LoginChanged>d__164.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\MainRegionViewModel.cs:行号 615

-----------------------------------------
时间:2017-11-08 10:41:20,865 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.LoginViewModel.<LoginManage_LoginChanged>d__24.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\LoginViewModel.cs:行号 126

-----------------------------------------
时间:2017-11-08 10:53:48,769 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.MainRegionViewModel.<LoginManage_LoginChanged>d__164.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\MainRegionViewModel.cs:行号 615

-----------------------------------------
时间:2017-11-08 10:53:49,168 
级别:ERROR 
类名:AIC.DatabaseService.LoginUserService
文件:D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs 第288行
日志内容:登录异常
-----------------------------------------

System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   在 AIC.LocalConfiguration.SignalProcess.InitSignals() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.SignalProcess\SignalProcess.cs:行号 104
   在 AIC.DatabaseService.LoginUserService.<SetUserLogin>d__23.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.DatabaseService\LoginUserService.cs:行号 158
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 AIC.HomePage.ViewModels.LoginViewModel.<LoginManage_LoginChanged>d__24.MoveNext() 位置 D:\SupportProject\AIC_HUD\AICHUD\AIC.HomePage\ViewModels\LoginViewModel.cs:行号 126
